### ISSUE TITLE
Logger transports for elastic gets deleted when there is an error writing the logs to Elasticsearch

### ISSUE THREAD

**Issue by masoomaf** [vanthome/winston-elasticsearch#103]
When there is an error writing logs to the elasticsearch (for example writing different types for a field), the error subscription is invoked the first time successfully. However on subsequent errors, the logger fails with the error "[winston ]Attempt to write logs with no transports"
The reason is because the elastic transport in the logger gets deleted after the exception.

```
var logger = winston.createLogger({
  transports: [
    new Elasticsearch(esTransportOpts)
  ],
  exitOnError: false
});

logger .on('error', (err) => {
    // elastic transport is deleted in logger object
    console.log('error writing to elasticsearch');
});

```

Expected Results: The transport should not be deleted after the exception.

**Comment by vanthome** [comment]
hmm, that's strange. In the code the transport is not deleted. Maybe that's a standard behaviour from Winston. Can you check this yourself?

**Comment by kjellmorten** [comment]
I think I have had the same problem, where the transport stops logging after an error from the ElasticSearch server. It seems to be a an intended feature, though:

https://github.com/vanthome/winston-elasticsearch/blob/f3839b9429f397a1a95cbb4e7e9a5a1736e511e9/bulk_writer.js#L123

👆This is called within `client.bulk().catch()`.

Is this really a good choice? Wouldn't it be better to log the error and keep going?

(For some context, my service will from time to time log too much data, resulting in a http error from ElasticSearch that again cause `Winston-elasticsearch` to stop logging. I should of course prevent this from happening in the first place, but when it does I certainly don't want logging to stop completely.)

**Comment by kjellmorten** [comment]
I see now that the `this.checkEsConnection` is supposed to start the transport again, but it doesn't seem to work. I'll have to look more into this to figure out why. Sorry about that.

**Comment by jlsbi** [comment]
I have the same problem.
Whenever there is a log that cannot reach my Elasticsearch node for any reason, I get the right error, but when the next log is being pushed, I get this error: "Attempt to write logs with no transports".
Thus, anytime an Elasticsearch transport cannot reach its node once, it is removed from the array of transports inside Winston.
Of course, this only happens when I have only one transport left. When I have at least 2 and one gets removed following an error, I have no warning about that and I never ever know about the fact that one of my transports was removed!

**Comment by strafe89** [comment]
@vanthome this issue appeared after these changes:
https://github.com/vanthome/winston-elasticsearch/commit/819de70f4f62d4f23c86438b0de5bf3a889786a8#diff-3805ebf53854d461672e5b174ef6a719

when you emit an error it just unpipes the stream and the transport closes immediately.
https://github.com/nodejs/readable-stream/blob/master/lib/_stream_readable.js#L702
if you comment this line, transport won't be closed.
from the other side, we want to be notified about elasticsearch errors, so probably you can just replace `error` event with `warn` or something. 
the issue seems really critical, please take a look at it.

**Comment by davidonet** [comment]
Same issue for me. The transport lacks of resiliency. My device connect to es server with GSM modem, it can he heratic. Even with big retry number, if I get a 400 error code from my server the system stop logging...

**Comment by rutemja** [comment]
In our project this issue lead to "Unhandled Rejection at Promise" errors which is critical for us.
@vanthome Can you already estimate when you will have time to look at this?

**Comment by vanthome** [comment]
Sorry guys I had no time to look into this yet. I think to emit a `warn` event is the second best option only as it's not a well defined event and is against intuition. I think we should re-pipe the source as described here: https://stackoverflow.com/a/33388016/1821792
Any obligations?

**Comment by bruegth** [comment]
@vanthome But doesn't it that mean that then this has to be handled from the outside of the Transport?

**Comment by vanthome** [comment]
no, the stream can handle that internally. I hope I can deliver this in the coming days.

**Comment by vanthome** [comment]
I have pushed the changes to GH only for now. Can someone maybe test this approach and provide feedback?

**Comment by bruegth** [comment]
@vanthome I've tested your changes, but unfortunately the node process will be killed by uncaught exception, while I'm restarting elasticsearch:
`
2020-05-18T08:40:26.125Z Warn: Elasticsearch LogTransport error (ConnectionError)! <--[on('error' handler of Transport]

2020-05-18T08:40:26.126Z Fatal: Uncaught Exception thrown
ConnectionError: connect ECONNREFUSED 172.28.32.5:9200
    at ClientRequest.<anonymous> (/app/node_modules/@elastic/elasticsearch/lib/Connection.js:103:18)
    at ClientRequest.emit (events.js:311:20)
    at Socket.socketErrorListener (_http_client.js:426:9)
    at Socket.emit (events.js:311:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)`

Maybe Elasticsearch client will reconnect, if it get repiped?

**Comment by bruegth** [comment]
@strafe89 @kjellmorten @davidonet Can someone of you, maybe test the current master too?

**Comment by vanthome** [comment]
I can reproduce the error (only this scenario I have tried) when I run the tests and ES is not even started. The issue why we see an `UnhandledPromiseRejectionWarning` is that I cannot see how to handle this error properly when using promises. I have therefore raised this:

https://github.com/elastic/elasticsearch-js/issues/1204

**Comment by Munawwar** [comment]
I've been looking into this. So far that is what I found.
Winston Logger inherits from readable-stream's Transform class. And emitting an error from that class throws exception. (and if you throw any error inside of a promise or a promise catch, like in bulk_writer.js, it will become an unhandled promise rejection)

Minimal example:
```js
const { Transform } = require('readable-stream');

process.on('unhandledRejection', (error) => {
  console.log('unhandledRejection');
  console.error(error);
});
process.on('uncaughtException', (error) => {
  console.log('uncaughtException');
  console.error(error);
});

const s = new Transform();
(async () => {
  s.emit('error', 'boom again!`');
  console.log("won't execute");
})();
s.emit('error', 'boom!`');
console.log("won't execute");
```

So how is it reaching there?
`thiz.transport.emit('error', e)` from BulkWriter.prototype.write() at bulk_writer.js
->
```
this.on('error', (err) => {
    this.source.pipe(this); // re-pipes readable
});
```
at index.js
->
`this.emit(event, err, transport);` in _onEvent function at winston/lib/winston/logger.js
->
kaboom!

I think we should avoid 'error' event... unless the logger dies during initialization or something critical like that... in every other case, we use our own event name.. maybe `warn`? `#error`?

**Comment by vanthome** [comment]
The scenario I have outlined that ES ist not started when the logger is started is covered meanwhile, there is no `UnhandledPromiseRejectionWarning` anymore.
For the cases where the ES connection dies during operation, this `emit()` here is causing the `UnhandledPromiseRejectionWarning`:
https://github.com/vanthome/winston-elasticsearch/blob/master/bulk_writer.js#L168
As @Munawwar noted above it's caused by the re-emission of the event within the winston logger.
I have slightly optimized the error handling in the test here
https://github.com/vanthome/winston-elasticsearch/blob/master/test/test.js#L44
and with that you can prevent the `UnhandledPromiseRejectionWarning`. I think this is quite adequate for production code and at this point merely a matter of documentation (I will improve this).
As for using another even like `warn` I don't like that because `error` is well established and even has a semantic meaning for node.
I will release the module in its current state tomorrow.

**Comment by Razzeee** [comment]
I guess the test you commented out in https://github.com/vanthome/winston-elasticsearch/commit/a8f68b03147924d33b61e678c4edfd61262f189c should be reinstated then?
