### ISSUE TITLE
Elasticsearch is not a function in version 0.8.8

### ISSUE THREAD

**Issue by mmihic96** [vanthome/winston-elasticsearch#131]
![image](https://user-images.githubusercontent.com/28544145/78825395-32321680-79e0-11ea-88cd-0ddb59bf3576.png)

**Comment by haggholm** [comment]
I think they re-introduced the problem fixed in 0.8.6: https://github.com/vanthome/winston-elasticsearch/issues/127

Basically,

* it used to export the transport only as the default export
* it changed to a named export
* this broke the package for everyone using the default
* some people dealt with this by using the named export
* it reverted to using the default export, since it broke so many dependencies
* so it broke for everyone who had switched to the named export…

I think at this point, because both versions are out there in the wild, the best thing to do would be to provide the same class as _both_ the default export _and_ as a named export, with a comment documenting why.

**Comment by mmihic96** [comment]
@haggholm I saw it after my post. I using naming export. 
Thank you anyhow.

**Comment by tobias-tengler** [comment]
Would be nice if breaking changes like this could be released as part of a major version increment in the future!

**Comment by vanthome** [comment]
I'm only for named exports. At this point people have migrated by now.

@tobias-tengler  will do so.
