### ISSUE TITLE
Memory limit for buffering of messages?

### ISSUE THREAD

**Issue by bradisbell** [vanthome/winston-elasticsearch#72]
From the documentation:

> Buffering of messages in case of inavailability of ES. The limit is the memory as all unwritten messages are kept in memory.

Can this be disabled?  Or, can a reasonable limit be configurable?

I'd hate to have my process crashing due to an Elasticsearch failure or connectivity issue.

**Comment by vanthome** [comment]
Actually, I think it's not completely accurately documented, because node will only grab ~2 GiB by default and you must explicitly increase it with ` --max-old-space-size=` otherwise.
So there is a limit. But to prevent the process crashing as you describe it can only be solved by limiting the consumed memory.
The problem with this, however, is that it's very hard (I think) to find out how much memory an array of messages actually consumes.
A solution with trade offs could be to just specify a maximum number of buffered messages; beyond this limit messages would be discarded then. What do you think? I'm open for a PR for this feature ;)

**Comment by bradisbell** [comment]
Yes, I think a max number of buffered messages would be fine.

Your point about a PR is well-taken.  I'll see if I can't take a crack at this next week.

**Comment by Snelius30** [comment]
Disable buffering option would be good.

**Comment by jooj123** [comment]
is this controlled by the `bufferLimit` parameter ? Or is that for something else ?

We are coming across memory issues when using this library - would be great to limit the amount of memory it consumes (not even sure why it needs to buffer so much?)

**Comment by vanthome** [comment]
Yes it is: https://github.com/vanthome/winston-elasticsearch#options
I will close this issue now.
